CONTIKI_PROJECT = my_first
all: $(CONTIKI_PROJECT)

 #UIP_CONF_IPV6=1
CONTIKI_WITH_RIME = 1
CONTIKI = ../..

TARGETDIRS += ../targets
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include


